export const APP_PERMISSIONS = {
  dashboardView: 'dashboard.view',
  companiesView: 'companies.view',
  companiesManage: 'companies.manage',
  productsView: 'products.view',
  productsManage: 'products.manage',
  categoriesView: 'categories.view',
  categoriesManage: 'categories.manage',
  brandsView: 'brands.view',
  brandsManage: 'brands.manage',
  inventoryView: 'inventory.view',
  inventoryAdjust: 'inventory.adjust',
  inventoryMovementsView: 'inventory-movements.view',
  salesView: 'sales.view',
  salesCreate: 'sales.create',
  /** Anular ventas y cierres de caja. */
  salesManage: 'sales.manage',
  customersView: 'customers.view',
  customersManage: 'customers.manage',
  usersView: 'users.view',
  usersCreate: 'users.create',
  usersEdit: 'users.edit',
  reportsView: 'reports.view',
  auditView: 'audit.view',
  settingsManage: 'settings.manage',
  plansManage: 'plans.manage',
  notificationsView: 'notifications.view',
  companyProfileView: 'company-profile.view',
  companyPlanView: 'company-plan.view',
  localesView: 'locales.view',
  localesManage: 'locales.manage',
  suppliersView: 'suppliers.view',
  suppliersManage: 'suppliers.manage',
  goodsReceiptsView: 'goods-receipts.view',
  goodsReceiptsManage: 'goods-receipts.manage',
  replenishmentView: 'replenishment.view',
} as const;

export type AppPermission = (typeof APP_PERMISSIONS)[keyof typeof APP_PERMISSIONS];
