export const PLAN_FEATURES = {
  sales: 'SALES',
  clients: 'CLIENTS',
  products: 'PRODUCTS',
  categories: 'CATEGORIES',
  brands: 'BRANDS',
  stock: 'STOCK',
  inventoryMovements: 'INVENTORY_MOVEMENTS',
  suppliers: 'SUPPLIERS',
  goodsReceipts: 'GOODS_RECEIPTS',
  supplyAnalytics: 'SUPPLY_ANALYTICS',
  abcAnalysis: 'ABC_ANALYSIS',
  reports: 'REPORTS',
  audit: 'AUDIT',
  notifications: 'NOTIFICATIONS',
} as const;

export const PLAN_FEATURE_LABELS: Readonly<Record<string, string>> = {
  SALES: 'Ventas y punto de venta',
  CLIENTS: 'Clientes',
  PRODUCTS: 'Productos',
  CATEGORIES: 'Categorías',
  BRANDS: 'Marcas',
  STOCK: 'Inventario',
  INVENTORY_MOVEMENTS: 'Movimientos de inventario',
  SUPPLIERS: 'Proveedores',
  GOODS_RECEIPTS: 'Ingreso de mercadería',
  SUPPLY_ANALYTICS: 'Abastecimiento y rotación',
  ABC_ANALYSIS: 'Clasificación ABC',
  REPORTS: 'Reportes',
  AUDIT: 'Auditoría',
  NOTIFICATIONS: 'Notificaciones',
};
