import { NotificationItem } from '../models/notification-item.model';

/** Placeholder data — no backend endpoint for notifications yet. */
export const NOTIFICATION_MOCK: readonly NotificationItem[] = [
  {
    id: '1',
    priority: 'ALTA',
    category: 'Empresas',
    title: 'Empresa suspendida automáticamente',
    body: 'MiniMarket Express superó 30 días sin pago. Plan Esencial registrado.',
    timeAgo: 'Hace 10 min',
    read: false,
    actions: ['Ver empresa', 'Reactivar'],
  },
  {
    id: '2',
    priority: 'MEDIA',
    category: 'Suscripciones',
    title: 'Plan por vencer',
    body: 'Comercial Andina: plan Negocio vence en 7 días hábiles.',
    timeAgo: 'Hace 25 min',
    read: false,
    actions: ['Ver empresa', 'Renovar'],
  },
  {
    id: '3',
    priority: 'INFO',
    category: 'Empresas',
    title: 'Nueva empresa registrada',
    body: 'Digital Shop SAC se registró exitosamente en el plan Esencial.',
    timeAgo: 'Hace 1 hora',
    read: false,
    actions: ['Ver empresa'],
  },
  {
    id: '4',
    priority: 'ALTA',
    category: 'Límites de plan',
    title: 'Límite de vendedores alcanzado',
    body: 'TechStore Perú alcanzó el límite de 3/3 vendedores permitidos en el plan Negocio.',
    timeAgo: 'Hace 2 horas',
    read: true,
    actions: ['Ver empresa', 'Upgrade plan'],
  },
  {
    id: '5',
    priority: 'MEDIA',
    category: 'Seguridad',
    title: 'Intento de login sospechoso',
    body: 'Se detectaron 5 intentos fallidos desde la IP 45.67.89.12 para el usuario jperez.',
    timeAgo: 'Hace 3 horas',
    read: true,
    actions: ['Ver auditoría', 'Bloquear IP'],
  },
  {
    id: '6',
    priority: 'SISTEMA',
    category: 'Sistema',
    title: 'Backup completado',
    body: 'Respaldo diario de base de datos completado exitosamente. 2.4 GB procesados.',
    timeAgo: 'Hace 5 horas',
    read: true,
    actions: [],
  },
  {
    id: '7',
    priority: 'SISTEMA',
    category: 'Sistema',
    title: 'Actualización programada',
    body: 'Mantenimiento preventivo v2.5.1 programado para el día 05/09/2026 02:00 AM.',
    timeAgo: 'Hace 1 día',
    read: true,
    actions: [],
  },
];
